apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitwarden.com/
    chart: self-host
    targetRevision: 2025.1.0
    helm:
      values: |
        component.scim.enabled: false
        general.domain: vault.lab.homelabz.xyz
        general.ingress.enabled: false
        general.ingress.cert.tls.name: tls-secret
        general.ingress.cert.tls.clusterIssuer: letsencrypt-staging
        general.email.replyToEmail: vault@homelabz.xyz
        general.email.smtpHost: smtp.gmail.com
        general.email.smtpPort: 587
        general.email.smtpSsl: true
        enableCloudCommunication: false
        cloudRegion: US
        sharedStorageClassName: ceph-block
        secrets.secretName: custom-secret
        database.enabled: true
        volume.logs.enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
