{{- if .Values.apps.issuers }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issuers
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/skywalkw3r/talos-klube.git
    path: app/charts/issuers
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
{{- end }}
