apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.9
    # helm:
    #   values: |
    #     configInline:
    #       address-pools:
    #       - name: 5-dvs-servers
    #         protocol: layer2
    #         addresses:
    #         - 10.5.5.195-10.5.5.200
    #       l2-advertisements:
    #       - name: default
    #         ipAddressPools:
    #         - 5-dvs-servers
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
