apiVersion: v1
kind: Service
metadata:
  namespace: rook-ceph
  name: rook-ceph-web
spec:
  selector:
    app: rook-ceph-mgr
    mgr_role: active
    rook_cluster: rook-ceph
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer